config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :appointments
  resources :doctors
  resources :patients do
    resources :appointments
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
    belongs_to :doctor
    belongs_to :patient
    accepts_nested_attributes_for :patient, reject_if: :all_blank

    # def patient_attributes=(patient_attributes)
    #     patient = Patient.find_or_create_by(patient_attributes)
    #     self.patient = patient
    #     save
    # end
end

app/models/doctor.rb
class Doctor < ApplicationRecord
    has_secure_password
    has_many :appointments
    has_many :patients, through: :appointments
end

app/models/patient.rb
# frozen_string_literal: true

class Patient < ApplicationRecord
    #validates :name, :phone_number, :age, :address, presence: true
    #validates :phone_number, length: {is: 10}
    has_many :appointments
    has_many :doctors, through: :appointments
    before_validation :make_name_case

    def self.search(query)
      where("name like ?", "%#{query}%")
    end

    private

    def make_name_case
        self.name = self.name.titlecase
    end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  def current_user
    @current_user ||= Doctor.last
  end
end

app/controllers/appointments_controller.rb
# frozen_string_literal: true

class AppointmentsController < ApplicationController
  before_action :set_appointment, only: %i[show edit update destroy]
  include AppointmentsHelper

  def index
    @appointments = if params[:patient_id]
                      Appointment.where(patient_id: params[:patient_id])
                    else
                      Appointment.all
                    end
  end

  def show; end

  def new
    @patient = Patient.find_by_id(params[:patient_id]) if params[:patient_id]
    @appointment = Appointment.new
  end

  def edit; end

  def create
    #   byebug
    @appointment = current_user.appointments.build(appointment_params)
    if @appointment.save
      redirect_to appointment_path(@appointment)
    else
      render 'new'
    end
  end

  private

  def set_appointment
    @appointment = Appointment.find(params[:id])
  end

  def appointment_params
    params.require(:appointment).permit(:time, :date, :notes, :doctor_id, :patient_id, patient_attributes: %i[name age phone_number address])
  end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:show, :edit, :update, :destroy]

  def new
    @doctor = Doctor.new(doctor_params)
  end

  def index
    @doctors = Doctor.all
  end

  def edit
  end

  def create
    @doctor = Doctor.new(doctor_params)
    if @doctor.save
      redirect_to @doctor
    else
      @errors = @doctor.errors.full_messages
      render "new"
    end
  end

  def show
  end

  def update
    if @doctor.update(doctor_params)
      redirect_to @doctor
    else
      render "edit"
    end
  end

  def destroy
    @doctor.destroy
    redirect_to doctors_url
  end


  private

  def set_doctor
    @doctor = Doctor.find(params[:id])
  end

  def doctor_params
    params.require(:doctor).permit(:user_name)
  end
end

app/controllers/patients_controller.rb
# frozen_string_literal: true

class PatientsController < ApplicationController
  before_action :set_patient, only: %i[show edit update destroy]

  def index
    @patients = if params[:q]
                  Patient.search(params[:q])
                else
                  Patient.all
                end
  end

  def show; end

  def new
    @patient = Patient.new
  end

  def edit; end

  def create
    @patient = Patient.new(patient_params(:name, :phone_number, :age, :address))
    if @patient.save
      redirect_to @patient

    else

      render 'new'
    end
  end

  def update
    if @patient.update(patient_params(:name, :phone_number, :age, :address))
      redirect_to @patient
    else
      render 'edit'
    end
  end

  def destroy
    @patient.destroy
    redirect_to patients_url
  end

  private

  def set_patient
    @patient = Patient.find(params[:id])
  end

  def patient_params(*args)
    params.require(:patient).permit(*args)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
    
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
    
    def current_user
        @current_user = Doctor.last
    end

end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper

end

app/views/appointments/_form.html.erb
<%=form_for(appointment) do |f|%>
    <label>Select Established Patient</label>
    <p><%=f.collection_select :patient_id, Patient.all, :id, :name, include_blank: true%></p>

    # Not sure if I want to keep a patient association in this partial.

    <h2>Appointment Details</h2>
    <label>Time: </label>
    <p><%=f.time_field :time%></p>
    <label>Date: </label>
    <p><%=f.date_field :date%></p>
    <label>Notes: </label>
    <p><%=f.text_area :notes%></p>
    <%=f.submit%>
    <%end%>

app/views/appointments/index.html.erb
<%=link_to "New Appointment", new_appointment_path%>
<h1>Appointments</h1>
<h3>
  <% @appointments.order(date: :desc).order(:time).each do |a| %>
    <%=a.date%>
    <li><%=link_to a.patient.name, appointment_path(a)%></li>
  <% end %>
</h3>

app/views/appointments/new.html.erb
<%if @patient%>
  <h1>New Appointment for <%=@patient.name%></h1>
<%else%>
  <h1>New Appointment</h1>
<%end%>
<%=form_for @appointment do |f|%>
  <%if @patient%>
    <%=f.hidden_field :patient_id, value:@patient.id%>
  <%else%>
    <label>Select Established Patient</label>
    <p><%=f.collection_select :patient_id, Patient.all, :id, :name, include_blank: true%></p>
    <b><label>Or, New Patient</label></b>
    <%=f.fields_for :patient, Patient.new do |patient_fields| %>
      <p><label>Name:</label></p>
      <p><%=patient_fields.text_field :name%></p>
      <label>Phone Number: (numbers only, ex. 1234567891)</label>
      <p><%=patient_fields.phone_field :phone_number%></p>
      <label>Age:</label>
      <p><%=patient_fields.number_field :age%></p>
      <label>Address:</label>
      <p><%=patient_fields.text_area :address%></p>
    <%end%>
  <%end%>
  <h2>Appointment Details</h2>
  <label>Time: </label>
  <p><%=f.time_field :time%></p>
  <label>Date: </label>
  <p><%=f.date_field :date%></p>
  <label>Notes: </label>
  <p><%=f.text_area :notes%></p>
  <%=f.submit%>
<%end%>

app/views/appointments/show.html.erb
<h1>Appointment for <%=@appointment.patient.name%></h1>
<h3>Patient: <%= link_to @appointment.patient.name, patient_path(@appointment.patient) if @appointment.patient%></h3>

<p><%=@appointment.time%></p>
<p><%=@appointment.date%></p>
<p><%=@appointment.notes%></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pod3Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/patients/_form.html.erb
<%=form_for(patient) do |f|%>
    <p><label>Name:</label></p>
    <p><%=f.text_field :name%></p>
    <label>Phone Number: (numbers only, ex. 1234567891)</label>
    <p><%=f.phone_field :phone_number%></p>
    <label>Age:</label>
    <p><%=f.number_field :age%></p>
    <label>Address:</label>
    <p><%=f.text_area :address%></p>
  <%=f.submit%>
  <%end%>

app/views/patients/edit.html.erb
<h1>Edit Patient Form</h1>

<% if @patient.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@patient.errors.count, "error") %>
      prohibited this post from being saved:
    </h2>
 
    <ul>
    <% @patient.errors.full_messages.each do |msg| %>
      <li><p style="color:red"><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= render partial: 'form', locals: {patient: @patient} %>

app/views/patients/index.html.erb
<%= link_to "New Patient", new_patient_url %>

<h1>Patient Index</h1>
<h3><% @patients.order(:name).each do |patient| %>
  <p><%=link_to patient.name, patient_path(patient)%></p>
<% end %></h3>

<%= form_tag(patients_path, method: "get") do %>
  <%= label_tag(:q, "Search for:") %>
  <%= text_field_tag(:q) %>
  <%= submit_tag("Search") %>
<% end %>

app/views/patients/new.html.erb
<h1>New Patient Form</h1>

<% if @patient.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@patient.errors.count, "error") %>
      prohibited this post from being saved:
    </h2>
 
    <ul>
    <% @patient.errors.full_messages.each do |msg| %>
      <li><p style="color:red"><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= render partial: 'form', locals: {patient: @patient} %>

app/views/patients/show.html.erb
<%=link_to "Home", patients_path%>
<h1><%=@patient.name%></h1>
<p><b>Phone:</b> <%=number_to_phone(@patient.phone_number)%></p>
<p><b>Age:</b> <%=@patient.age%></p>
<p><b>Address: </b><%=@patient.address%></p>
<%=link_to "All Appointments", patient_appointments_path(@patient)%>
<%=link_to "New Appointment", new_patient_appointment_path(@patient)%>
<%=link_to 'Edit Patient', edit_patient_path(@patient)%><br>
<br>
<%= button_to("Delete Patient", @patient, {:onclick => "return confirm('Are you sure?')", :method => :delete, :remote => true}) %>